version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build: .
    command: /app/stopandsearch -config-file=/app/conf/config.json
    volumes:
      - .:/go/src/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    links:
      - db