version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker


  app:
    build: .
    command: ["/app/stopandsearch"]
    environment:
      STOP_SEARCH_ENV: prod
      PG_HOST: db
      PG_USER: postgres
      PG_DBNAME: postgres
      PG_PASSWORD: docker
    volumes:
      - .:/go/src/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    links:
      - db